version: '3'

volumes:
  postgres_data:
    driver: local
  app_code:
    driver: local

services:
  # node-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - app_code:/app
  #   environment:
  #     - NODE_PORT=${NODE_PORT:-3000}
  #   ports:
  #     - "${NODE_PORT:-3000}:${NODE_PORT:-3000}"
  #   restart: unless-stopped

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kpi.com
      PGADMIN_DEFAULT_PASSWORD: pgpass
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
    expose:
      - 5050
    restart: unless-stopped
    